### ISSUE TITLE
Know of any other services?

### ISSUE THREAD

**Issue by HughP** [HughP/LinguisticsLibrarianList#8]
@cesine, @RichardLitt, @amundo, @jdurham, @Lingomat, @rtxanson and @jrwdunham

I stared a list of linguistic services which are offered through the web (both Browser based, and REST based). I am wondering if you might know of any more... 

https://github.com/HughP/LinguisticsLibrarianList/blob/master/LinguisticWebServices.md

**Comment by HughP** [comment]
Paul wrote me and suggested that I check out CLARIN services here: http://www.clarin.eu/content/web-services

**Comment by RichardLitt** [comment]
Smart. CLARIN is pretty awesome. I used to do some work for them when I was in Germany.

**Comment by HughP** [comment]
http://webservices-lst.science.ru.nl/

These are services hosted by our “Radboud University Nijmegen”, Netherlands.
It’s really computational linguistics, and there must be many, many similar services floating around.

Some of the most useful ones included:
UCTO - A tokenizer
FROG – A Dutch language text-in, tagging + dep. parsing output tool
FOWLT – Spell checking service (but there are much more competitors around, obviously)
TIMBL – Any memory-based linguistics experiments can be run using this web service (nice if you don’t want to (or can) install timbl yourself)

**Comment by HughP** [comment]
I copied these items into the services list. Create a new issue if needed to add more items to the services list.
