### ISSUE TITLE
Define services

### ISSUE THREAD

**Issue by RichardLitt** [HughP/LinguisticsLibrarianList#9]
What do you mean by that?

**Comment by HughP** [comment]
good call. I mean professional businesses which offer a service such as digitization of legacy materials (Reel-to-reel conversion to digital .wav formats, etc.). This is not a service in the sense of  a service running on a linux server.

**Comment by RichardLitt** [comment]
That needs to be clearer somewhere. I was completely wrong about what you wanted, in that case.

**Comment by HughP** [comment]
I just added a new document called [TerminologyUsed.md](https://github.com/HughP/LinguisticsLibrarianList/blob/master/TerminologyUsed.md) is that a good way to handle terms and meanings or should terms be added to the same document in a preamble kind of way?

**Comment by RichardLitt** [comment]
I would put them in the main document, but it depends on the expected users. Users will have to know to click on other documents, and I'm not sure how much your expected user is familiar with GitHub.

**Comment by HughP** [comment]
Good points. Thanks. I suppose you mean #10 when you say

> I was completely wrong about what you wanted...

Or did you have something else in mind?

**Comment by RichardLitt** [comment]
Yeah, I meant #10. And my understanding of what you wanted, too. :)

**Comment by HughP** [comment]
I moved the referenced document and integrated it to the LLL preamble. So I am considering "services" as being defined and this issue (and the confusion I created) cleared up.
